/**
 * Client-side data export — CSV (hand-rolled) and Excel (.xlsx via SheetJS).
 *
 * The whole site is a static export, so there is no server to render a download:
 * every file is generated in the browser from data already on the page. Every
 * export carries the dataset's provenance (source · as-of · confidence) — a CSV
 * header block and a dedicated "Provenance" sheet in Excel — because the buy-side
 * audience needs to trust (and cite) the numbers in their own models.
 *
 * `xlsx` is **dynamically imported inside `exportXlsx`** so it is code-split into
 * its own chunk and never bloats the initial bundle (CSV needs no dependency).
 */
import type { Confidence, SourceRef } from "@/data/types/core";

/** A primitive cell value. Numbers stay raw (unformatted) by default. */
export type ExportValue = string | number | boolean | null | undefined;

/** One export row, keyed by `ColumnDef.key`. */
export type ExportRow = Record<string, ExportValue>;

/**
 * An export column. `label` is the human header; `format` is optional — by
 * default numbers export raw so they drop straight into a model.
 */
export interface ColumnDef {
  key: string;
  label: string;
  format?: (value: ExportValue) => string;
}

/**
 * Provenance + identity for an export, normally derived from a `Snapshot`
 * envelope via {@link snapshotMeta}. Either supply rich `sources` (preferred)
 * or a simple `source` + `confidence` pair.
 */
export interface ExportMeta {
  section: string;
  dataset: string;
  /** ISO date (`snapshot.updatedAt`) — drives the filename + provenance. */
  asOf: string;
  /** Rich per-source provenance from the snapshot envelope. */
  sources?: SourceRef[];
  /** Simple single-source label (when `sources` is not supplied). */
  source?: string;
  /** Single confidence level (when `sources` is not supplied). */
  confidence?: Confidence;
  /** Optional methodology / coverage notes appended to the provenance. */
  notes?: string[];
}

/** One worksheet in a (possibly multi-dataset) Excel workbook. */
export interface ExportSheet {
  name: string;
  columns: ColumnDef[];
  rows: ExportRow[];
  /** Per-sheet provenance (for "Export all" workbooks); falls back to the top-level meta. */
  meta?: ExportMeta;
}

const GENERATED_BY = (date: string) =>
  `Generated by Solardash on ${date} — figures tagged 'modelled' are Solardash estimates.`;

/** Today's date, ISO `YYYY-MM-DD`. Wall-clock is fine — this stamps the export, not committed data. */
function today(): string {
  return new Date().toISOString().slice(0, 10);
}

/** Build an `ExportMeta` from a snapshot envelope, reusing its provenance. */
export function snapshotMeta(
  snap: { section: string; dataset: string; updatedAt: string; sources: SourceRef[] },
  overrides?: { section?: string; dataset?: string; notes?: string[] },
): ExportMeta {
  return {
    section: overrides?.section ?? snap.section,
    dataset: overrides?.dataset ?? snap.dataset,
    asOf: snap.updatedAt,
    sources: snap.sources,
    notes: overrides?.notes,
  };
}

/** slug-safe filename token. */
function slug(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/** `solardash-<section>-<dataset>-<asOf>.<ext>` */
export function exportFilename(meta: ExportMeta, ext: "csv" | "xlsx"): string {
  return `solardash-${slug(meta.section)}-${slug(meta.dataset)}-${slug(meta.asOf)}.${ext}`;
}

/** Render one cell to a string for CSV (raw unless a `format` is given). */
function cellText(value: ExportValue, format?: ColumnDef["format"]): string {
  if (format) return format(value);
  if (value == null) return "";
  return String(value);
}

/** Quote a CSV field when it contains a comma, quote, or newline. */
function csvField(s: string): string {
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

/** Tabular CSV (header row of labels + one line per row). No provenance — see {@link exportCsv}. */
export function toCsv(columns: ColumnDef[], rows: ExportRow[]): string {
  const head = columns.map((c) => csvField(c.label)).join(",");
  const body = rows.map((r) =>
    columns.map((c) => csvField(cellText(r[c.key], c.format))).join(","),
  );
  return [head, ...body].join("\r\n");
}

/** The provenance lines that precede a CSV / fill the Excel "Provenance" sheet. */
function provenanceRows(meta: ExportMeta): string[][] {
  const out: string[][] = [["Dataset", "Source", "As of", "Confidence", "Note"]];
  const label = `${meta.section} / ${meta.dataset}`;
  if (meta.sources && meta.sources.length > 0) {
    for (const s of meta.sources) {
      out.push([label, s.name, s.asOf, s.confidence, s.note ?? ""]);
    }
  } else {
    out.push([label, meta.source ?? "—", meta.asOf, meta.confidence ?? "", ""]);
  }
  return out;
}

/** Trigger a browser download for a string or binary payload. */
export function downloadBlob(
  content: string | ArrayBuffer | Uint8Array,
  filename: string,
  mime: string,
): void {
  const blob = new Blob([content as BlobPart], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  a.rel = "noopener";
  document.body.appendChild(a);
  a.click();
  a.remove();
  // Revoke on the next tick so the download has started.
  setTimeout(() => URL.revokeObjectURL(url), 0);
}

/** Export a single table as CSV with a provenance header block prepended. */
export function exportCsv(opts: {
  filename?: string;
  columns: ColumnDef[];
  rows: ExportRow[];
  meta: ExportMeta;
}): void {
  const { columns, rows, meta } = opts;
  const header: string[] = [
    `Solardash — ${meta.section} / ${meta.dataset}`,
    `As of: ${meta.asOf}`,
  ];
  if (meta.sources && meta.sources.length > 0) {
    for (const s of meta.sources) {
      header.push(`Source: ${s.name} (as of ${s.asOf}, ${s.confidence})`);
    }
  } else {
    if (meta.source) header.push(`Source: ${meta.source}`);
    if (meta.confidence) header.push(`Confidence: ${meta.confidence}`);
  }
  for (const n of meta.notes ?? []) header.push(`Note: ${n}`);
  header.push(GENERATED_BY(today()));

  const headerBlock = header.map((line) => csvField(line)).join("\r\n");
  const csv = `${headerBlock}\r\n\r\n${toCsv(columns, rows)}\r\n`;
  downloadBlob(
    csv,
    opts.filename ?? exportFilename(meta, "csv"),
    "text/csv;charset=utf-8",
  );
}

/** Sheet names: ≤31 chars, no illegal chars, unique within the workbook. */
function sheetName(name: string, used: Set<string>): string {
  let base = name.replace(/[\\/?*[\]:]/g, " ").trim().slice(0, 31) || "Sheet";
  let candidate = base;
  let i = 2;
  while (used.has(candidate.toLowerCase())) {
    const suffix = ` ${i++}`;
    base = name.slice(0, 31 - suffix.length);
    candidate = `${base}${suffix}`;
  }
  used.add(candidate.toLowerCase());
  return candidate;
}

/**
 * Export one or more datasets to a single `.xlsx` workbook plus a "Provenance"
 * sheet. `xlsx` is dynamically imported here so it is code-split out of the
 * initial bundle.
 */
export async function exportXlsx(opts: {
  filename?: string;
  sheets: ExportSheet[];
  meta: ExportMeta;
}): Promise<void> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();
  const used = new Set<string>();

  for (const sheet of opts.sheets) {
    const header = sheet.columns.map((c) => c.label);
    const body = sheet.rows.map((r) =>
      sheet.columns.map((c) =>
        // Keep numbers numeric for Excel; only stringify when a formatter is set.
        c.format ? c.format(r[c.key]) : (r[c.key] ?? null),
      ),
    );
    const ws = XLSX.utils.aoa_to_sheet([header, ...body]);
    XLSX.utils.book_append_sheet(wb, ws, sheetName(sheet.name, used));
  }

  // Provenance sheet — one block per dataset (each sheet's meta, else top-level).
  const provAoa: (string | number)[][] = [
    [`Solardash export — ${opts.meta.section}`],
    [GENERATED_BY(today())],
    [],
  ];
  const metas = opts.sheets.map((s) => s.meta ?? opts.meta);
  const seen = new Set<string>();
  let first = true;
  for (const m of metas) {
    const id = `${m.section}/${m.dataset}`;
    if (seen.has(id)) continue;
    seen.add(id);
    const block = provenanceRows(m);
    if (!first) provAoa.push([]);
    first = false;
    for (const row of block) provAoa.push(row);
  }
  const provWs = XLSX.utils.aoa_to_sheet(provAoa);
  XLSX.utils.book_append_sheet(wb, provWs, sheetName("Provenance", used));

  const out = XLSX.write(wb, { bookType: "xlsx", type: "array" }) as ArrayBuffer;
  downloadBlob(
    out,
    opts.filename ?? exportFilename(opts.meta, "xlsx"),
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  );
}

/** Build chart export columns/rows from category data (`{ label, value }[]`). */
export function categoryToExport(
  data: { label: string; value: number }[],
  categoryLabel: string,
  valueLabel: string,
): { columns: ColumnDef[]; rows: ExportRow[] } {
  return {
    columns: [
      { key: "category", label: categoryLabel },
      { key: "value", label: valueLabel },
    ],
    rows: data.map((d) => ({ category: d.label, value: d.value })),
  };
}

/**
 * Build chart export columns/rows for a stacked/grouped category chart — one
 * column per series (unit folded into the header), one row per category.
 */
export function categoriesToExport(
  categories: string[],
  series: { key: string; label: string; unit?: string; values: (number | null | undefined)[] }[],
  categoryLabel: string,
): { columns: ColumnDef[]; rows: ExportRow[] } {
  const columns: ColumnDef[] = [
    { key: "category", label: categoryLabel },
    ...series.map((s) => ({
      key: s.key,
      label: s.unit ? `${s.label} (${s.unit})` : s.label,
    })),
  ];
  const rows: ExportRow[] = categories.map((c, i) => {
    const row: ExportRow = { category: c };
    for (const s of series) row[s.key] = s.values[i] ?? null;
    return row;
  });
  return { columns, rows };
}
